name: Update and PR

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "0 0 */14 * *"  # Runs every 14 days at midnight
  workflow_dispatch:

jobs:
  update-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Run update script
        run: bash update.sh

      - name: Set Branch Name
        id: set_branch
        run: echo "BRANCH_NAME=auto/update-$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Auto-update $(date +'%Y-%m-%d')"
          branch: ${{ env.BRANCH_NAME }}
          title: "Auto-update $(date +'%Y-%m-%d')"
          body: "This PR was created automatically by GitHub Actions on $(date +'%Y-%m-%d')"
          token: ${{ secrets.GITHUB_TOKEN }}
